Add missing conversion class from vector of WheelTelemetryData to Python list
Add missing conversion class from vector of WheelTelemetryData to Python list

This adds a missing conversion from vector of WheelTelemetryData to a Python list. When trying to access the "wheels" attribute of the VehicleTelemetryData without this, this exception will occur:

TypError: No to_python (by-value) converter found for C++ type: std::vector<carla::rpc::WheelTelemetryData, std::allocator<carla::rpc::WheelTelemetryData>>

This addition fixes this issue to make the usage in line with similar classes such as "VehiclePhysicsControl" and "WheelPhysicsControl" 

Checklist:
- [x] Your branch is up-to-date with the dev branch and tested with latest changes.
- [x] Extended the README/documentation, if necessary.
- [x] Code compiles correctly.
- [x] All tests passing with make check.